2024_SEU_Graduates_Big_Data/urls.py
# from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.urls import include, path

from django_cas_ng import views as cas_views

urlpatterns = [
    # path("admin/", admin.site.urls),
    # ----- STATIC FILES ----- #
    path("favicon.ico", serve, kwargs={"path": "favicon.ico"}),
    # ----- CAS ----- #
    path("accounts/login/", cas_views.LoginView.as_view(), name="cas_ng_login"),
    path("accounts/logout/", cas_views.LogoutView.as_view(), name="cas_ng_logout"),
    # ----- APPS ----- #
    path("health_check", include("app_health_check.urls")),
    path("demo/", include("app_demo.urls")),
    path("", include("app_main.urls")),
]

# # ----- DEBUG TOOLBAR ----- #
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app_demo/urls.py
from django.urls import path

from . import views

app_name = "app_demo"
urlpatterns = [
    path("", views.welcome_view, name="welcome_view"),
    path("personal_view", views.personal_view, name="personal_view"),
]

graduates_big_data/urls.py
from django.contrib import admin
from django.urls import include, path

from django_cas_ng import views as cas_views

urlpatterns = [
    path("admin/", admin.site.urls),
    # ----- CAS ----- #
    path("accounts/login/", cas_views.LoginView.as_view(), name="cas_ng_login"),
    path("accounts/logout/", cas_views.LogoutView.as_view(), name="cas_ng_logout"),
    # ----- APPS ----- #
    path("error/", include("error.urls")),
    path("health_check", include("app_health_check.urls")),
    path("", include("app_main.urls")),
]

app_demo/views/personal_view.py
from django.shortcuts import render


def personal_view(request):
    return render(
        request,
        "demo_personal_view.html",
    )

app_demo/views/welcome_view.py
from django.shortcuts import render


def welcome_view(request):
    return render(
        request,
        "demo_welcome_view.html",
    )

app_main/views/personal_view.py
from django.shortcuts import render

from app_main.models import (
    BorrowingRankStat,
    FavoriteCanteenStat,
    GraduatePersonalStat,
    LibraryBorrowingStat,
    OrderingRankStat,
    SportsCompetitionStat,
)
from django_cas_ng.decorators import login_required

# 毕业生总数
GRADUATE_TOTAL_NUM = -1
# 显示借阅量排名的阈值（前50%才显示）
SHOW_BORROWING_RANK_THRESHOLD = 0.5
# 最高借阅量
MAX_BORROWING_NUM = -1


@login_required
def personal_view(request):
    # 获取当前用户的一卡通号
    seu_card_id = request.user.username
    # # 非内测用户，显示提示信息
    # with open("./test_users.txt", "r") as f:
    #     test_users = f.read().splitlines()
    # if seu_card_id not in test_users:
    #     return render(request, "welcome_view.html", {"is_eligible": False})
    # 若不在毕业生数据中，则显示提示信息
    if (
        not GraduatePersonalStat.objects.only("seu_card_id")
        .filter(seu_card_id=seu_card_id)
        .exists()
    ):
        return render(request, "welcome_view.html", {"is_eligible": False})

    # 查询指定毕业生的个人统计信息
    graduate = GraduatePersonalStat.objects.get(seu_card_id=seu_card_id)

    # 毕业生总数
    global GRADUATE_TOTAL_NUM
    if GRADUATE_TOTAL_NUM == -1:
        GRADUATE_TOTAL_NUM = GraduatePersonalStat.objects.count()

    # 全校最高借阅量
    global MAX_BORROWING_NUM
    if MAX_BORROWING_NUM == -1:
        MAX_BORROWING_NUM = BorrowingRankStat.objects.order_by("borrowing_rank")[
            0
        ].borrowing_num

    # 最常去相同食堂的人数
    same_favorite_canteen_percent = get_favorite_canteen_percent(
        graduate.most_frequent_consumption_place
    )

    # 图书馆相关统计信息（借阅量排名、本学院借阅量第一名）
    show_borrowing_rank, borrowing_rank_percent, top_borrower_in_unit = (
        get_library_stat(graduate.total_borrowed_books_num, graduate.unit_name)
    )

    # 场馆预约次数排名
    gym_ordering_rank_percent = get_gym_stat(graduate.gym_ordered_times)

    # 体育竞赛信息
    show_sports_competitions, sports_competition = get_sports_competition_stat(
        seu_card_id
    )

    return render(
        request,
        "personal_view.html",
        {
            "graduate": graduate,
            "same_favorite_canteen_percent": same_favorite_canteen_percent,
            "show_borrowing_rank": show_borrowing_rank,
            "borrowing_rank_percent": borrowing_rank_percent,
            "max_total_borrowed_books_num": MAX_BORROWING_NUM,
            "top_borrower_in_unit": top_borrower_in_unit,
            "gym_ordering_rank_percent": gym_ordering_rank_percent,
            "show_sports_competitions": show_sports_competitions,
            "sports_competition": sports_competition,
        },
    )


def get_favorite_canteen_percent(most_frequent_consumption_place):
    """计算最常去相同食堂的人数百分比"""
    if not most_frequent_consumption_place:
        same_favorite_canteen_percent = "0.00%"
    else:
        same_favorite_canteen_cnt = FavoriteCanteenStat.objects.get(
            canteen_name=most_frequent_consumption_place
        ).count
        same_favorite_canteen_percent = (
            f"{same_favorite_canteen_cnt / GRADUATE_TOTAL_NUM:.2%}"
        )

    return same_favorite_canteen_percent


def get_library_stat(total_borrowed_books_num, unit_name):
    """计算图书馆相关统计信息（借阅量排名、本学院借阅量第一名）"""
    # 借阅量排名
    if not total_borrowed_books_num or int(total_borrowed_books_num) == 0:
        show_borrowing_rank = False
        borrowing_rank_percent = "0.00%"
    else:
        # 检查排名表中是否有该借阅量（处理两表数据未同步的情况）
        if (
            BorrowingRankStat.objects.only("borrowing_num")
            .filter(borrowing_num=total_borrowed_books_num)
            .exists()
        ):
            borrowing_rank = BorrowingRankStat.objects.get(
                borrowing_num=total_borrowed_books_num
            ).borrowing_rank
        # 若不存在则用最邻近的借阅量的排名代替
        else:
            borrowing_rank = (
                BorrowingRankStat.objects.filter(
                    borrowing_num__lt=total_borrowed_books_num
                )
                .order_by("-borrowing_num")[0]
                .borrowing_rank
            )
        # 判断是否显示借阅量排名并计算排名百分比
        show_borrowing_rank = (
            borrowing_rank / GRADUATE_TOTAL_NUM < SHOW_BORROWING_RANK_THRESHOLD
        )
        borrowing_rank_percent = f"{1 - (borrowing_rank - 1) / GRADUATE_TOTAL_NUM:.2%}"

    # 本学院借阅量第一名
    if (
        not unit_name
        or not LibraryBorrowingStat.objects.only("unit_name")
        .filter(unit_name=unit_name)
        .exists()
    ):
        top_borrower_in_unit = None
    else:
        top_borrower_in_unit = LibraryBorrowingStat.objects.filter(
            unit_name=unit_name
        ).order_by("rank")[0]

    return show_borrowing_rank, borrowing_rank_percent, top_borrower_in_unit


def get_gym_stat(gym_ordered_times):
    """计算体育场馆相关统计信息（场馆预约次数排名）"""
    # 预约次数排名
    if not gym_ordered_times or int(gym_ordered_times) == 0:
        ordering_rank_percent = "0.00%"
    else:
        # 检查排名表中是否有该预约次数（处理两表数据未同步的情况）
        if (
            OrderingRankStat.objects.only("ordering_times")
            .filter(ordering_times=gym_ordered_times)
            .exists()
        ):
            ordering_rank = OrderingRankStat.objects.get(
                ordering_times=gym_ordered_times
            ).ordering_rank
        # 若不存在则用最邻近的预约次数的排名代替
        else:
            ordering_rank = (
                OrderingRankStat.objects.filter(ordering_times__lt=gym_ordered_times)
                .order_by("-ordering_num")[0]
                .ordering_rank
            )
        # 计算排名百分比
        ordering_rank_percent = f"{1 - (ordering_rank - 1) / GRADUATE_TOTAL_NUM:.2%}"

    return ordering_rank_percent


def get_sports_competition_stat(seu_card_id):
    """获取体育竞赛信息"""
    sports_competition_list = SportsCompetitionStat.objects.filter(
        seu_card_id=seu_card_id
    )
    show_sports_competitions = bool(sports_competition_list)
    sports_competition = (
        sports_competition_list.order_by("?")[0] if show_sports_competitions else None
    )

    return show_sports_competitions, sports_competition

app_main/views/welcome_view.py
from django.shortcuts import render

from app_main.models import GraduatePersonalStat
from django_cas_ng.views import LoginView


def welcome_view(request):
    # 若用户未通过 CAS 认证，则跳转至 CAS 登录页面
    if not request.user.is_authenticated or not request.user.username:
        return LoginView.as_view()(request)

    # 检查是否为本届毕业生，若不在毕业生数据中，则跳转到错误页面，显示仅对本届毕业生开放的提示
    seu_card_id = request.user.username
    is_eligible = True
    graduate_name = None
    if (
        not GraduatePersonalStat.objects.only("seu_card_id")
        .filter(seu_card_id=seu_card_id)
        .exists()
    ):
        is_eligible = False
    else:
        graduate_name = (
            GraduatePersonalStat.objects.only("seu_card_id", "full_name")
            .get(seu_card_id=seu_card_id)
            .full_name
        )

    # # 内测用户检查
    # with open("./test_users.txt", "r") as f:
    #     test_users = f.read().splitlines()
    # if seu_card_id not in test_users:
    #     is_eligible = False

    return render(
        request,
        "welcome_view.html",
        {
            "is_eligible": is_eligible,
            "graduate_name": graduate_name,
        },
    )

stat_data/views/personal_view.py
from django.shortcuts import redirect, render

from django_cas_ng.decorators import login_required
from stat_data.models import (
    BorrowingRankStat,
    FavoriteCanteenStat,
    GraduatePersonalStat,
    LibraryBorrowingStat,
    SportsCompetitionStat,
)

# 显示借阅量排名的阈值（前50%才显示）
SHOW_BORROWING_RANK_THRESHOLD = 0.5


@login_required
def personal_view(request):
    # 获取当前用户的一卡通号
    seu_card_id = request.user.username
    # 若不在毕业生数据中，则显示提示信息
    if not GraduatePersonalStat.objects.filter(seu_card_id=seu_card_id).exists():
        return redirect("error:not_eligible_view")

    # 查询指定毕业生的个人统计信息
    graduate = GraduatePersonalStat.objects.get(seu_card_id=seu_card_id)

    # 毕业生总数
    graduate_total_num = GraduatePersonalStat.objects.count()

    # 最常去相同食堂的人数
    if not graduate.most_frequent_consumption_place:
        same_favorite_canteen_percent = "0.00%"
    else:
        same_favorite_canteen_cnt = FavoriteCanteenStat.objects.get(
            canteen_name=graduate.most_frequent_consumption_place
        ).count
        same_favorite_canteen_percent = (
            f"{same_favorite_canteen_cnt / graduate_total_num:.2%}"
        )

    # 借阅量排名
    if not graduate.total_borrowed_books_num:
        show_borrowing_rank = False
        borrowing_rank_percent = "0.00%"
    else:
        borrowing_rank = BorrowingRankStat.objects.get(
            borrowing_num=graduate.total_borrowed_books_num).borrowing_rank
        show_borrowing_rank = borrowing_rank / graduate_total_num < SHOW_BORROWING_RANK_THRESHOLD
        borrowing_rank_percent = f"{1 - borrowing_rank / graduate_total_num:.2%}"

    # 全校最高借阅量
    max_total_borrowed_books_num = BorrowingRankStat.objects.order_by("borrowing_rank")[0].borrowing_num

    # 本学院借阅量第一名
    if not graduate.unit_name:
        top_borrower_in_unit = None
    else:
        unit_name = graduate.unit_name
        same_unit_borrowers = (
            LibraryBorrowingStat.objects.filter(unit_name=unit_name)
            .extra(
                select={
                    "total_borrowed_books_num_int": "CAST(total_borrowed_books_num AS SIGNED INTEGER)"
                }
            )
            .order_by("-total_borrowed_books_num_int")
        )
        top_borrower_in_unit = same_unit_borrowers[0] if same_unit_borrowers else None

    # 场馆预约次数排名
    if not graduate.gym_ordered_times:
        gym_ordering_rank_percent = "0.00%"
    else:
        gym_ordering_rank = GraduatePersonalStat.objects.filter(
            gym_ordered_times=graduate.gym_ordered_times
        ).count()
        gym_ordering_rank_percent = f"{1 - gym_ordering_rank / graduate_total_num:.2%}"

    # 是否显示体育竞赛
    sports_competition_list = SportsCompetitionStat.objects.filter(
        seu_card_id=seu_card_id
    )
    show_sports_competitions = bool(sports_competition_list)
    sports_competition = (
        sports_competition_list[0] if show_sports_competitions else None
    )

    return render(
        request,
        "personal_view.html",
        {
            "graduate": graduate,
            "same_favorite_canteen_percent": same_favorite_canteen_percent,
            "show_borrowing_rank": show_borrowing_rank,
            "borrowing_rank_percent": borrowing_rank_percent,
            "max_total_borrowed_books_num": max_total_borrowed_books_num,
            "top_borrower_in_unit": top_borrower_in_unit,
            "gym_ordering_rank_percent": gym_ordering_rank_percent,
            "show_sports_competitions": show_sports_competitions,
            "sports_competition": sports_competition,
        },
    )

stat_data/views/welcome_view.py
from django.shortcuts import redirect, render

from django_cas_ng.views import LoginView
from stat_data.models import GraduatePersonalStat


def welcome_view(request):
    # 若用户未通过 CAS 认证，则跳转至 CAS 登录页面
    if not request.user.is_authenticated or not request.user.username:
        return LoginView.as_view()(request)

    # 检查是否为本届毕业生，若不在毕业生数据中，则跳转到错误页面，显示仅对本届毕业生开放的提示
    seu_card_id = request.user.username
    if not GraduatePersonalStat.objects.filter(seu_card_id=seu_card_id).exists():
        return redirect("error:not_eligible_view")

    return render(request, "welcome_view.html")

app_demo/templates/demo_welcome_view.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="Resource-type" content="Document"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <title>【示例】东南大学 2024 毕业生大数据</title>

    {# 自定义 CSS #}
    <link rel="stylesheet" href="{% static 'app_main/css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'app_main/css/welcome_view.css' %}"/>
</head>

<body>
<main>
    {# 遮罩层（用于转场动画） #}
    <div id="overlay"></div>

    {# 背景图片 #}
    <img src="{% static 'app_main/images/0-welcome/background.png' %}"
         alt="background image (welcome)"
         class="bg-img"/>

    <div class="width-limiter">
        <div class="fg-content"
             style="top: 0;opacity: 1;-moz-opacity: 1;">
            {# 顶部文字 #}
            <div id="text-1">
                <p>&nbsp;&nbsp;&nbsp;&nbsp;时光流转，又是一年盛夏毕业季，</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;晓东同学，</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;你是否还记得那天第一次相遇？</p>
            </div>

            <div id="btn-area">
                {# 页面跳转按钮 #}
                <button id="jump-btn">
                    <img src="{% static 'app_main/images/0-welcome/jump-button.svg' %}"
                         alt="jump button"/>
                </button>

                {# 底部文字 #}
                <p id="text-2">回顾那些独特的校园时光</p>
            </div>

            <div id="bottom-content">
                {# 底部复选框 #}
                <input type="checkbox" id="agree-checkbox" name="agree-checkbox" value="agree"/>
                <label for="agree-checkbox">同意使用个人数据生成毕业生数据报告</label>
                {# 数据日期声明 #}
                <p id="data-date">本报告所用数据截至 2024 年 6 月 5 日</p>
            </div>
        </div>
    </div>
</main>

<script>
    // 使用js代替css媒体查询（企业微信、QQ不支持aspect-ratio的媒体查询，导致页面显示异常）
    let aspectRatio = window.innerWidth / window.innerHeight;

    // 根元素字体大小适配
    document.documentElement.style.fontSize = "3.75vw";
    if (aspectRatio > 53 / 100) {
        document.documentElement.style.fontSize = window.innerHeight * 1.8 / 100 + "px";
    }

    // 使用js实现媒体查询（企业微信不支持aspect-ratio的媒体查询）
    const calcSize = () => {
        // 宽屏适配
        if (aspectRatio > 53 / 100) {
            const fgContent = document.querySelectorAll(".fg-content");
            fgContent.forEach((item) => {
                item.style.width = "auto";
                item.style.aspectRatio = "48/100";
            });
        }
        if (aspectRatio > 75 / 100) {
            document.documentElement.style.width = "fit-content";
            const bgImg = document.querySelectorAll(".bg-img");
            bgImg.forEach((item) => {
                item.style.width = "auto";
            });
        }
    };

    // 企业微信、QQ、微信适配
    const ua = window.navigator.userAgent.toLowerCase();
    if (ua.indexOf("wxwork") !== -1 || ua.indexOf("qq") !== -1 || ua.indexOf("micromessenger") !== -1) {
        calcSize();
    }

    window.addEventListener("resize", () => {
        aspectRatio = window.innerWidth / window.innerHeight;
        // 根元素字体大小适配
        document.documentElement.style.fontSize = "3.75vw";
        if (aspectRatio > 53 / 100) {
            document.documentElement.style.fontSize = window.innerHeight * 1.8 / 100 + "px";
        }
        // 企业微信、QQ、微信适配
        if (ua.indexOf("wxwork") !== -1 || ua.indexOf("qq") !== -1 || ua.indexOf("micromessenger") !== -1) {
            calcSize();
        }
    });
</script>
<script>
    window.addEventListener("pageshow", () => {
        // 进入页面的转场动画
        document.getElementById("overlay").style.opacity = "0";
    });

    // 页面跳转按钮点击事件
    document.getElementById("jump-btn").addEventListener("click", (event) => {
        // 若用户未勾选同意复选框，弹出提示
        if (!document.getElementById("agree-checkbox").checked) {
            alert("请先勾选同意使用个人数据");
            event.preventDefault();
        }
        // 显示转场动画，执行页面跳转
        else {
            document.getElementById("overlay").style.opacity = "1";
            setTimeout(() => {
                window.location.href = "{% url 'app_demo:personal_view' %}";
            }, 1000);
        }
    });
</script>
</body>
</html>

app_demo/templates/personal_view.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="Resource-type" content="Document"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <title>【示例】东南大学 2024 毕业生大数据</title>

    {# Swiper CSS #}
    <link rel="stylesheet" href="{% static 'swiper-11.1.3/swiper-bundle.min.css' %}"/>
    {# 自定义 CSS #}
    <link rel="stylesheet" href="{% static 'app_main/css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'app_main/css/personal_view.css' %}"/>
</head>

<body>
<main>
    {# 遮罩层（用于转场动画） #}
    <div id="overlay"></div>

    <div class="swiper">
        <div class="swiper-wrapper">
            {# ---------- 场景1: 大门 ---------- #}
            <div class="swiper-slide" id="scenario-gate">
                {% include "slides/slide_1.html" %}
            </div>

            {# ---------- 场景2: 宿舍 ---------- #}
            <div class="swiper-slide" id="scenario-dormitory">
                {% include "slides/slide_2.html" %}
            </div>

            {# ---------- 场景3: 食堂 ---------- #}
            <div class="swiper-slide" id="scenario-canteen">
                {% include "slides/slide_3.html" %}
            </div>

            {# ---------- 场景4: 教室 ---------- #}
            <div class="swiper-slide" id="scenario-classroom">
                {% include "slides/slide_4.html" %}
            </div>

            {# ---------- 场景5: 报告厅 ---------- #}
            <div class="swiper-slide" id="scenario-auditorium">
                {% include "slides/slide_5.html" %}
            </div>

            {# ---------- 场景6: 图书馆 ---------- #}
            <div class="swiper-slide" id="scenario-library">
                {% include "slides/slide_6.html" %}
            </div>

            {# ---------- 场景7: 体育馆 ---------- #}
            <div class="swiper-slide" id="scenario-gym">
                {% include "slides/slide_7.html" %}
            </div>

            {# ---------- 场景8: 离开 ---------- #}
            <div class="swiper-slide" id="scenario-leave">
                {% include "slides/slide_8.html" %}
            </div>

            {# ---------- 结束 ---------- #}
            <div class="swiper-slide" id="end">
                {% include "slides/slide_9.html" %}
            </div>
        </div>
    </div>
</main>


{# Swiper JS #}
<script src="{% static 'swiper-11.1.3/swiper-bundle.min.js' %}"></script>
<script>
    let curSlide = null;
    let prevSlidePos = 0;
    let curSlidePos = 0;
    let nextSlidePos = 0;

    window.addEventListener("pageshow", () => {
        // 转场动画 - 进入页面
        document.getElementById("overlay").style.opacity = "0";
    });

    // Initialize Swiper
    const swiper = new Swiper(".swiper", {
        direction: "vertical",
        edgeSwipeDetection: "prevent",
        grabCursor: true,
        preventInteractionOnTransition: true,
        resistanceRatio: 0.5,
        speed: 800,
        threshold: 0,
        touchAngle: 90,
        virtual: {
            enabled: true,
        },
        on: {
            // 动画相关逻辑
            // 原因：如果只是把动画添加到class中，只会在第一次加载时生效，之后的页面切换不会触发动画
            init: function () {
                // 当前页面内容fadeIn
                const initFgContent = this.wrapperEl.querySelector(".swiper-slide-active .fg-content");
                initFgContent && (initFgContent.style.opacity = "1");
            },
            touchStart: function () {
                // 记录开始滑动时的页面
                curSlide = this.wrapperEl.querySelector(".swiper-slide-active");
                // 计算当前页、上一页、下一页的位置
                prevSlidePos = -1 * (this.activeIndex - 1) * this.height;
                curSlidePos = -1 * this.activeIndex * this.height;
                nextSlidePos = -1 * (this.activeIndex + 1) * this.height;
            },
            touchMove: function () {
                // 滑动距离小于阈值时不触发动画
                if ((this.translate >= curSlidePos && (this.translate - curSlidePos) / (prevSlidePos - curSlidePos) < 0.2)
                    || (this.translate <= curSlidePos && (this.translate - curSlidePos) / (nextSlidePos - curSlidePos) < 0.2)) {
                    return;
                }
                // 开始滑动时，隐藏该页内容
                const lastFgContent = curSlide.querySelector(".fg-content");
                lastFgContent && (lastFgContent.style.opacity = "0");
                // 结束页特殊处理
                if (curSlide.id === "end") {
                    const titleImg = lastFgContent.querySelector("#title-img-end");
                    const pic = curSlide.querySelector("#pic-end");
                    titleImg && (titleImg.style.animationName = "none");
                    pic && (pic.style.animationName = "fadeOutLeft");
                    pic && (pic.style.opacity = "0");
                }
            },
            slideChange: function () {
                // 隐藏前一页内容（处理没有触发touchMove中操作的情况）
                const lastFgContent = curSlide.querySelector(".fg-content");
                lastFgContent && (lastFgContent.style.opacity = "0");
                // 结束页特殊处理
                if (curSlide.id === "end") {
                    const titleImg = lastFgContent.querySelector("#title-img-end");
                    const pic = curSlide.querySelector("#pic-end");
                    titleImg && (titleImg.style.animationName = "none");
                    pic && (pic.style.animationName = "fadeOutLeft");
                    pic && (pic.style.opacity = "0");
                }
            },
            transitionEnd: function () {
                // 页面切换完成后，显示该页内容
                const newSlide = this.wrapperEl.querySelector(".swiper-slide-active");
                const newFgContent = newSlide.querySelector(".fg-content");
                newFgContent && (newFgContent.style.opacity = "1");
                // 结束页特殊处理
                if (newSlide.id === "end") {
                    const titleImg = newFgContent.querySelector("#title-img-end");
                    const pic = newSlide.querySelector("#pic-end");
                    titleImg && (titleImg.style.animationName = "tada");
                    pic && (pic.style.animationName = "fadeInLeft");
                    pic && (pic.style.opacity = "1");
                }
            },
        },
    });
</script>
</body>
</html>

app_demo/templates/welcome_view.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="Resource-type" content="Document"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <title>【示例】东南大学 2024 毕业生大数据</title>

    {# 自定义 CSS #}
    <link rel="stylesheet" href="{% static 'app_main/css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'app_main/css/welcome_view.css' %}"/>
</head>

<body>
<main>
    {# 遮罩层（用于转场动画） #}
    <div id="overlay"></div>

    {# 背景图片 #}
    <img src="{% static 'app_main/images/0-welcome/background.png' %}"
         alt="background image (welcome)"
         class="bg-img"/>

    <div class="width-limiter">
        <div class="fg-content"
             style="top: 0;opacity: 1;-moz-opacity: 1;">
            {# 顶部文字 #}
            <div id="text-1">
                <p>&nbsp;&nbsp;&nbsp;&nbsp;时光流转，又是一年盛夏毕业季，</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;晓东同学，</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;你是否还记得那天第一次相遇？</p>
            </div>

            <div id="btn-area">
                {# 页面跳转按钮 #}
                <button id="jump-btn">
                    <img src="{% static 'app_main/images/0-welcome/jump-button.svg' %}"
                         alt="jump button"/>
                </button>

                {# 底部文字 #}
                <p id="text-2">回顾那些独特的校园时光</p>
            </div>


            {# 底部复选框 #}
            <div id="bottom-content">
                <input type="checkbox" id="agree-checkbox" name="agree-checkbox" value="agree"/>
                <label for="agree-checkbox">同意使用个人数据生成毕业生数据报告</label>
            </div>
        </div>
    </div>
</main>

<script>
    window.addEventListener("pageshow", () => {
        // 推荐竖屏浏览提示
        if (window.innerWidth > window.innerHeight) {
            alert("推荐使用竖屏浏览");
        }
        // 进入页面的转场动画
        document.getElementById("overlay").style.opacity = "0";
    });

    // 页面跳转按钮点击事件
    document.getElementById("jump-btn").addEventListener("click", (event) => {
        // 若用户未勾选同意复选框，弹出提示
        if (!document.getElementById("agree-checkbox").checked) {
            alert("请先勾选同意使用个人数据");
            event.preventDefault();
        }
        // 显示转场动画，执行页面跳转
        else {
            document.getElementById("overlay").style.opacity = "1";
            setTimeout(() => {
                window.location.href = "{% url 'app_demo:personal_view' %}";
            }, 1000);
        }
    });
</script>
</body>
</html>